FROM apache/airflow:2.9.0

USER root

# iputils-ping used for testing, default-jdk needed to submit spark jobs
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         vim \
         iputils-ping \
         default-jdk \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install apache-airflow
RUN pip install apache-airflow-providers-apache-spark

COPY setup/airflow/establish_connection.sh .
